.travis.yml:
  sudo: true
  services:
  - docker
  addons:
    apt:
      packages:
      - debhelper # required for trusty VM
      - cmake
      - libgeoip-dev
      - protobuf-compiler
  deploy:
    access_key_id: AKIAINMB43VSSPFZISAA
    secret_access_key:
      secure: XM54WvZy2s/66WG8pFnOyY/b9nVQAAbvl7xQeG6WCwRDRhdAmbE1mAJMK+vH1NNIukAsDHqe+p3pHMkipf+hJyNA32xxCrApkgSfofhGjefrTVGhKu15GmDLomr0mINj0IIITU5FY0/A+weLLE25yXr1l1SlZW6juCCN0ScIneYOEC1yp8MrZNoHw+CrK4JvTwUty/9UoC04csPljC0I9mC78NH6HKxiyt5uh0DdQEJHHWyHW7z4ZpEkDLrHePkqFyD+uwJVdilbVGFYHhC0Kxd24NTuzRKpRsEExRjDfv0aMgO+G47xoLXz3fqYglPc3fm4yV+lmzE8k1lbmE6e8kAtzVU41axGNbuVvxbHjTclpfSrL1ODAL3nB/FXzvgPR/eLVOcIhOh1qzq62aBqEWWw6a3IzA4cmU5H9xtBlxkVlPrGIkN3Mq6oLZl026bsSqvf5Z3zeRjPoPRxpV81B4vOWcydZOi5As8t0MArKUKDGH6Nr3kEElWRsbtIzf5HiQZTYiK2E/ttgZ4/9j4XdTJwgV0DWtIKeBigi0jJjVZ881oPLLQa1u+ldlgbHoI7d5dloXpIj90zeOxYvIpjhWV7dlX0KxszBqqA5BaiSNAm/H8xmRTqp88Gprt9cf2lq4D/KOBus71MzWZ3bqzWH8qgfx95OGHXnotKXnVtG4s=
    api_key:
      secure: DHLLpsmmZp6lVl3qVenYAMASydHz07S8eVVGzTUHahRWkusJ+5AZwYjrCdL/TwkyaM3RFu1f/gyqyjCVr7pFUSqKhher7Xo59yKwIxCBK+bJb37JPre4mZTc3c6QMs5iKBSXj0xGjocjKM4LX9Ot/g8cdzIFh9zeMNUnneYT4ngcHNMmMo+U3Y9vR1g2nxRG4m48/LyQYVqsISzvBuEZD9LQpv1Vu8d+IIZ4Gj4g4TZtzTt+NHiA6woEQQukck3PvuXDOxgyx4xREo25GZWEfeQkOh3vkf1ck7svmT7hC8qSmCVbPTXiAhMJEnGRFRLcBOCOZzuf4ka0A7o/HbpO1uOXDJyD5YlfUgrgd4gE7GHHBQzqlSPZgi2dXIFN2rkQbO5b+q2UKZ3p2reoqt5osvuP7zNXox1z2oq7P+MHngVY+ULsef3nGTlq9MfIX+z9mN5w60uFMPTyBbsLjo9+npQsClRaJ0POciGGq3cxgcFFQSRtWh5xz7HQKL3+ROPUo5PfdFQY/CRt/95S5Jb6yX8wwU9k6ac94b+sKUYoQM25vNMBGVCwafOikDp7OvFiJQuMEAhgkKcOpDLLHTgvs3LfFVjEmoo2Cl0GUp5jjasWfljW8yos7uNkZwrmb5nDDU6f/J7HlmrOygjfmUmx8KmKOFYR+RH0/l9DbVRHEss=

scripts/build.sh:
   unmanaged: true
scripts/test.sh:
  unmanaged: true
Makefile:
  unmanaged: true
