.travis.yml:
  sudo: true
  services:
  - docker
  addons:
    apt:
      packages:
      - debhelper # required for trusty VM
      - cmake
      - libgeoip-dev
      - protobuf-compiler
  install:
    - cd $SNAP_PLUGIN_SOURCE
    - make
  env:
    global:
      - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
      - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
    matrix:
      - TEST=unit
      - TEST=integration
scripts/build.sh:
   unmanaged: true
scripts/test.sh:
  unmanaged: true
Makefile:
  unmanaged: true
